version: "3"
services:
  laravel:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NEWRELIC_LICENSE_KEY=${NEWRELIC_LICENSE_KEY}
        - PROJ=laravel_newrelic_example
    ports:
      - 8011:8000/tcp
